### ISSUE TITLE
bug: nagsuppressions for construct

### ISSUE THREAD

**Issue by maheshbr** [cdklabs/cdk-nag#1246] opened 2023-03-30 10:25 UTC
### What is the problem?

Using `NagSuppressions.addResourceSuppressions` sometimes doesn't suppress all the rules for the construct, and has to be applied to the stack.

### Reproduction Steps

Create a simple lambda construct with a policy to put records in a firehose stream and using the default `AWSLambdaBasicExecutionRole` policy.

Create a test, and add the following suppressions to the `testFunction`, where `testFunction` is an initialized construct
```javascript
NagSuppressions.addResourceSuppressions(
      testFunction,
      [
        {
          id: 'AwsSolutions-IAM4',
          reason: 'lorem ipsum',
        },
        {
          id: 'AwsSolutions-IAM5',
          reason: 'lorem ipsum',
        },
      ],
      true,
    )
```
to the constructor and also use 
```javascript
test('No unsuppressed Errors', () => {
    const errors = Annotations.fromStack(stack).findError(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*'),
    )
    console.log(
      JSON.stringify(
        errors.map((f) => f.entry.data),
        null,
        4,
      ),
    )

    expect(errors).toHaveLength(0)
  })
```
to the test

### What did you expect to happen?

Construct level suppressions to be enforced

### What actually happened?

Still returns cdk-nag errors related to `AwsSolutions-IAM4` and `AwsSolutions-IAM5`

### cdk-nag version

2.24.0

### Language

Typescript

**Comment by dontirun** [comment] 2023-03-30 13:42
How are the suppressions being applied in this case, in the test suite or in the actual stack/construct?

Additionally, can you provide a snippet to reproduce the error?

**Comment by maheshbr** [comment] 2023-04-04 08:40
Hi @dontirun Please find a snipped of the code we use to create lambda functions

```javascript
export class TestNodeJSFunction extends NodejsFunction {
  constructor(scope: Construct, id: string, props: NodeJSFunctionProps) {
    const accountId = '1123456789'
    const region = 'us-east-1'

    super(scope, id, {
      memorySize: 256,
      runtime: Runtime.NODEJS_16_X,
    })
  }
}
```

**Comment by dontirun** [comment] 2023-04-04 12:22
I can see from the `id` in the output that the error is not on the Lambda function you created but on the log retention custom resource (`/TestLambdaStack/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/DefaultPolicy/Resource`) created but the CDK.

Example 5 on the README will help you deal with that case if you choose to suppress it.

**Comment by maheshbr** [comment] 2023-04-04 14:41
Thanks for your help Arun @dontirun , using appliesTo at the stack level suppressed the error.

**Comment by dontirun** [comment] 2023-04-04 14:45
Awesome! You can also use path based suppressions if you don't want to suppress at a stack level.

Closing this issue since it seems to be resolved.

**Closed** 2023-04-04 14:45 UTC
Labels: guidance
